### ISSUE TITLE
Compiling SCSS and then require it.

### ISSUE THREAD

**Issue by adamleithp** [VaclavSynacek/react-isomorphic-static-site-generator-boilerplate#2]
Hey, I'm struggling with adding a SCSS framework to my static pages. It seems that on regular `require()`, within a component throws the error because the DOM has not rendered yet. 
`window is not defined`

Any idea how I would accomplish go about getting a `.scss` file compiled then required within a component?

**Comment by MessyFork** [comment]
If you're using webpack you can first push it through the sass-loader then have the css-loader handle it. 

The odd thing about the webpack loaders is that webpack pipes them from right to left
This is what I have.
`{
        test: /\.scss/,
        loader: ExtractTextPlugin.extract('css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass'),
        include: __dirname + '/src',
}`
The ExtractTextPlugin is a plugin to export CSS styles into a dedicated sheet. The querystring after css is just to create unique names.

For development you can use this instead (this example is also easier to see what I'm talking about):
`{
        test: /\.scss/,
        loader:'css!sass'),
        include: __dirname + '/src',
}`

good luck!
